//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicDataTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoachORStaff
    {
        public CoachORStaff()
        {
            this.CoachORStaffSports = new HashSet<CoachORStaffSport>();
        }
    
        public long CoachORStaffID { get; set; }
        public long UniversityID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string EmailAddress { get; set; }
        public string PhoneNo { get; set; }
        public string CellPhoneNo { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string State { get; set; }
        public string City { get; set; }
        public string Zip { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> ChangeDate { get; set; }
        public Nullable<bool> IsEmailQuestionnaire { get; set; }
        public Nullable<bool> ISAllowMultipleExport { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string UALogin { get; set; }
        public string UAPassword { get; set; }
        public Nullable<bool> IsComplianceOfficer { get; set; }
        public Nullable<bool> IsSmsReplyOnCellPhone { get; set; }
        public Nullable<bool> IsDynApprovedSender { get; set; }
        public bool IsCalBdayActive { get; set; }
        public string Photo { get; set; }
        public Nullable<int> IsAdmissionUser { get; set; }
        public string TwilioPhoneNumber { get; set; }
        public long LoginAttempts { get; set; }
        public Nullable<System.DateTime> LoginAttemptDate { get; set; }
        public byte IsMessengerUser { get; set; }
        public byte IsAthleticDirector { get; set; }
    
        public virtual University University { get; set; }
        public virtual ICollection<CoachORStaffSport> CoachORStaffSports { get; set; }
    }
}
