//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicDataTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoachORStaffSport
    {
        public long CoachSportID { get; set; }
        public long CoachORStaffID { get; set; }
        public long SportID { get; set; }
    
        public virtual CoachORStaff CoachORStaff { get; set; }
        public virtual Sport Sport { get; set; }
    }
}
