//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicDataTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sport
    {
        public Sport()
        {
            this.CoachORStaffSports = new HashSet<CoachORStaffSport>();
        }
    
        public long SportID { get; set; }
        public long UniversityID { get; set; }
        public string SportName { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> ChangeDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsUAActive { get; set; }
        public Nullable<long> RuleGroupID { get; set; }
        public Nullable<long> CompliancePeriodID { get; set; }
        public bool IsFootball { get; set; }
        public string Organization { get; set; }
        public string Division { get; set; }
        public Nullable<bool> IsRSAllowed { get; set; }
    
        public virtual ICollection<CoachORStaffSport> CoachORStaffSports { get; set; }
    }
}
