//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicDataTest
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Dev_Frontrush_RailsEntities6 : DbContext
    {
        public Dev_Frontrush_RailsEntities6()
            : base("name=Dev_Frontrush_RailsEntities6")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<University> Universities { get; set; }
        public DbSet<Sport> Sports { get; set; }
        public DbSet<CoachORStaff> CoachORStaffs { get; set; }
        public DbSet<CoachORStaffSport> CoachORStaffSports { get; set; }
    }
}
